### PR TITLE
feat: not found page & Routing

### PR DESCRIPTION
**Pull request by HarshnaNHaswani**
please review

### CODE REVIEW

**Comment by ashifkhn** [comment]
Everything is working fine. Good to go.

**Comment by ashifkhn** [comment]
Add the link if you can I had to clone the repo.

**Review by ivinayakg — APPROVED** [review]
great for creating route objects

**Comment by HarshnaNHaswani** [comment]
thank you @ashifkhn @ivinayakg  for the review!

**Pull request merged**
